//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EC2AMAZ-APRE02I\\SQLEXPRESS;Initial Catalog=dbGTIntegration;User ID=db" +
            "Owner;Password=AnurotecSiesa2021;Integrated Security=False")]
        public string ConexionGT {
            get {
                return ((string)(this["ConexionGT"]));
            }
            set {
                this["ConexionGT"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/GTIntegration/ServiciosWeb/wsGenerarPlano.asmx")]
        public string Infraestructura_Anurotec_wsGenerarPlano {
            get {
                return ((string)(this["Infraestructura_Anurotec_wsGenerarPlano"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/GTIntegration/ServiciosWeb/wsGenerarPlano.asmx")]
        public string Infraestructura_ConsumoGT_wsGenerarPlano {
            get {
                return ((string)(this["Infraestructura_ConsumoGT_wsGenerarPlano"]));
            }
        }
    }
}
